name: TypeNote Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Client Dependencies
      working-directory: ./client
      run: |
        npm install
        npm install @reduxjs/toolkit react-redux
        npm install slate slate-react
        npm install tailwindcss postcss autoprefixer
        npm install @tailwindcss/typography
        npm install material-icons
        npm install react-resizable @types/react-resizable

    - name: Setup Client Config Files
      working-directory: ./client
      run: |
        # 初始化 tailwind
        npx tailwindcss init -p
        
        # 确保 public 目录存在
        mkdir -p public
        
        # 下载必要的静态文件
        curl https://raw.githubusercontent.com/facebook/create-react-app/main/packages/cra-template/template/public/favicon.ico -o public/favicon.ico
        curl https://raw.githubusercontent.com/facebook/create-react-app/main/packages/cra-template/template/public/logo192.png -o public/logo192.png
        curl https://raw.githubusercontent.com/facebook/create-react-app/main/packages/cra-template/template/public/logo512.png -o public/logo512.png

    - name: Build Client
      working-directory: ./client
      run: |
        CI=false npm run build

    - name: Test Client
      working-directory: ./client
      run: |
        npm test -- --passWithNoTests

    # 如果需要部署，可以添加部署步骤
    # - name: Deploy
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     # 部署命令
